services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PHP_VERSION=8.3
      - NODE_VERSION=22.14
      - REVERSE_PROXY=false
      - USER_ID=1000
      - GROUP_ID=1000
    ports:
      - "8888:80"
    volumes:
      - ./www:/var/www/html
