name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      php_versions:
        description: 'PHP versions to build (comma-separated)'
        required: false
        default: '8.2,8.3'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.2', '8.3']
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.php_version }}
            type=raw,value=latest,enable=${{ matrix.php_version == '8.3' }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            NODE_VERSION=22.14
          cache-from: type=gha
          cache-to: type=gha,mode=max
